server:
  tomcat:
    connection-timeout: 5000

spring:
  application:
    name: hearu

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 5000
      data-source-properties:
        connectTimeout: 5000
        socketTimeout: 10000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

oauth:
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
  google:
    client-id: ${GOOGLE_CLIENT_ID}

jwt:
  access-token:
    expire-time: ${ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token:
    expire-time: ${REFRESH_TOKEN_EXPIRE_TIME}
  secret-key: ${JWT_SECRET_KEY}

llm:
  completion-url: ${LLM_COMPLETION_URL}
  api-key: ${LLM_API_KEY}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

scheduler:
  refresh-token:
    cleanup:
      cron: "0 0 3 * * *"

management:
  endpoints:
    web:
      exposure:
        include: health