spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info
    com.example.hearu: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true